version: '3.8'

services:
  proxy-converter:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    container_name: telegram-proxy-converter